"""Physics helper utilities for spectral conversions."""

from .augment import augment_radiance, random_swirlike_atmosphere
from .planck import (
    K_B,
    C,
    H,
    band_averaged_radiance,
    bt_K_to_radiance,
    bt_sample_to_radiance_sample,
    bt_spectrum_to_radiance,
    bt_to_radiance,
    inverse_planck_central_lambda,
    planck_radiance_wavelength,
    radiance_sample_to_bt_sample,
    radiance_spectrum_to_bt,
    radiance_to_bt,
    radiance_to_bt_K,
)
from .rad_reflectance import (
    radiance_sample_to_toa_reflectance,
    radiance_to_toa_reflectance,
    toa_reflectance_sample_to_radiance,
    toa_reflectance_to_radiance,
)
from .resampling import (
    convolve_to_bands,
    generate_gaussian_srf,
    interpolate_to_centers,
    SyntheticSensorConfig,
    simulate_virtual_sensor,
)
from .continuum import (
    BandDefinition,
    BandMetrics,
    build_continuum,
    compute_band_area,
    compute_band_asymmetry,
    compute_band_depth,
    compute_band_metrics,
    compute_composite_depth_ratio,
    compute_convex_hull_continuum,
    continuum_remove,
)
from .rt_regime import (
    SWIRRegime,
    attach_swir_regime,
    classify_rt_regime,
    classify_swir_regime,
    swir_regime_for_sample,
    swir_regime_for_scene,
    trusted_swir,
)
from .tes import (
    bt_spectrum_to_radiance_spectrum,
    compute_lwir_emissivity_proxy,
    lwir_pipeline_for_sample,
    radiance_spectrum_to_bt_spectrum,
    tes_lwirt,
)
from .solar import (
    earth_sun_distance_au,
    earth_sun_distance_for_sample,
    esun_for_sample,
    get_reference_esun,
    project_esun_to_bands,
)
from .swir import band_depth, radiance_to_reflectance, reflectance_to_radiance
from .swir_avirisng import (
    avirisng_bad_band_mask,
    radiance_to_reflectance_avirisng,
    reflectance_to_radiance_avirisng,
)

__all__ = [
    "K_B",
    "C",
    "H",
    "augment_radiance",
    "avirisng_bad_band_mask",
    "band_depth",
    "BandDefinition",
    "BandMetrics",
    "build_continuum",
    "band_averaged_radiance",
    "bt_K_to_radiance",
    "bt_sample_to_radiance_sample",
    "bt_spectrum_to_radiance",
    "bt_to_radiance",
    "SWIRRegime",
    "attach_swir_regime",
    "classify_rt_regime",
    "classify_swir_regime",
    "compute_band_area",
    "compute_band_asymmetry",
    "compute_band_depth",
    "compute_band_metrics",
    "compute_composite_depth_ratio",
    "compute_convex_hull_continuum",
    "compute_lwir_emissivity_proxy",
    "convolve_to_bands",
    "continuum_remove",
    "generate_gaussian_srf",
    "get_reference_esun",
    "interpolate_to_centers",
    "inverse_planck_central_lambda",
    "lwir_pipeline_for_sample",
    "planck_radiance_wavelength",
    "bt_spectrum_to_radiance_spectrum",
    "radiance_to_bt",
    "radiance_sample_to_bt_sample",
    "radiance_spectrum_to_bt",
    "radiance_spectrum_to_bt_spectrum",
    "radiance_to_bt_K",
    "radiance_to_toa_reflectance",
    "radiance_to_reflectance",
    "radiance_to_reflectance_avirisng",
    "SyntheticSensorConfig",
    "radiance_sample_to_toa_reflectance",
    "simulate_virtual_sensor",
    "random_swirlike_atmosphere",
    "reflectance_to_radiance",
    "reflectance_to_radiance_avirisng",
    "tes_lwirt",
    "earth_sun_distance_au",
    "earth_sun_distance_for_sample",
    "project_esun_to_bands",
    "esun_for_sample",
    "toa_reflectance_sample_to_radiance",
    "toa_reflectance_to_radiance",
    "trusted_swir",
    "swir_regime_for_sample",
    "swir_regime_for_scene",
]
